version: "3"

services:
  postgres:
    image: postgres:14-alpine
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - node_skeleton:/data

volumes:
  node_skeleton: